# AUTO-HUNTER QUERIES - NO LINKS NEEDED - SCRIPT SEARCHES ON ITS OWN
mode: auto_hunt
youtube_queries:
    - Officer Tatum Nolan Wells interview
    - Nolan Wells friend interview WLOX
    - Nolan Wells friend interview WXXV
    - Nolan Wells Sun Herald interview
    - Horn Island July 4th Nolan Wells
    - Horn Island search team video
    - Jackson County Sheriff Nolan Wells
mdmr:
  auto_search: true
  portal: https://dmr.ms.gov
scanner:
  auto_search: true
  queries:
        - Jackson County dispatch July 4 2026
        - Sea Tow Ocean Springs July 4
